import { useState, useEffect } from 'react'

import './Popup.css'
import { HistoryItem } from '../types'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const [history, setHistory] = useState<any[]>([])

  useEffect(() => {
    // 获取历史记录
    chrome.storage.local.get('history').then((result) => {
      setHistory(result.history || [])
    })
  }, [])

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])
  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank" className='link'>
        generated by create-chrome-ext
      </a>
      {
        history.map((item: HistoryItem) => (
          <div key={item.timestamp} className='history-item'>
            <div className='history-item-content'>
              <h3>{item.title}</h3>
              <a href={item.url}>goTo</a>
            </div>
          </div>
        ))
      }
    </main>
  )
}

export default Popup
