import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const [history, setHistory] = useState<any[]>([])

  useEffect(() => {
    // 获取历史记录
    chrome.storage.local.get('history').then((result) => {
      setHistory(result.history || [])
    })
  }, [])

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <ul>
        {history.map((h: any) => {
          return <li>
            <span>{h.url}</span>
            <span>{h.title}</span>
          </li>
        })}
      </ul>
    </main>
  )
}

export default Popup
