import React, { useState, useEffect } from 'react'
import './NewTab.css'

interface Collection {
  id: number;
  styled_html: string;
  date: string;
  created_at: string;
}

const TWITTER_CSS_URL = 'https://abs.twimg.com/responsive-web/client-web-legacy/main.1e0e9d5.css'; // 可根据需要更新

export const NewTab = () => {
  const getTime = () => {
    const date = new Date()
    const hour = String(date.getHours()).padStart(2, '0')
    const minute = String(date.getMinutes()).padStart(2, '0')
    return `${hour}:${minute}`
  }

  const [time, setTime] = useState(getTime())
  const [collections, setCollections] = useState<Collection[]>([])
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  useEffect(() => {
    let intervalId = setInterval(() => {
      setTime(getTime())
    }, 1000)
    return () => {
      clearInterval(intervalId)
    }
  }, [])

  useEffect(() => {
    fetch('http://localhost:8000/api/v1/collections/list')
      .then(res => res.json())
      .then(data => setCollections(data))
      .catch(() => setCollections([]))
  }, [])

  return (
    <section>
      <span></span>
      <h1>{time}</h1>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <div className="tweet-collection-list">
        {collections.map(col => (
          <div key={col.id} className="tweet-html-wrap" style={{margin: '2em 0', width: '550px', border: '1px solid #eee', borderRadius: '12px', background: 'black', overflow: 'auto'}}>
            <div dangerouslySetInnerHTML={{ __html: col.styled_html }} />
          </div>
        ))}
      </div>
    </section>
  )
}

export default NewTab
